package entrypoint

import (
	"github.com/ggmolly/belfast/internal/answer"
	"github.com/ggmolly/belfast/internal/connection"
	"github.com/ggmolly/belfast/internal/packets"
	"github.com/ggmolly/belfast/internal/protobuf"
	"google.golang.org/protobuf/proto"
)

var validRegions = map[string]interface{}{
	"CN": nil,
	"EN": nil,
	"JP": nil,
	"KR": nil,
	"TW": nil,
}

func registerPackets() {
	packets.RegisterPacketHandler(10800, []packets.PacketHandler{answer.HandleUpdateCheck})
	packets.RegisterPacketHandler(10700, []packets.PacketHandler{answer.GatewayPackInfo})
	packets.RegisterPacketHandler(8239, []packets.PacketHandler{answer.WriteServerListHTTPResponse})
	packets.RegisterPacketHandler(10020, []packets.PacketHandler{answer.HandleAuthConfirm})
	packets.RegisterLocalizedPacketHandler(10802, packets.LocalizedHandler{
		CN: &[]packets.PacketHandler{answer.BuildServerInterconnectionResponse},
		TW: &[]packets.PacketHandler{answer.BuildServerInterconnectionResponse},
		JP: &[]packets.PacketHandler{answer.BuildServerInterconnectionResponse},
		KR: &[]packets.PacketHandler{answer.BuildServerInterconnectionResponse},
	})
	packets.RegisterPacketHandler(10018, []packets.PacketHandler{answer.HandleServerStateCheck})
	packets.RegisterPacketHandler(10022, []packets.PacketHandler{answer.JoinServer})
	packets.RegisterPacketHandler(10024, []packets.PacketHandler{answer.CreateNewPlayer})
	packets.RegisterPacketHandler(10026, []packets.PacketHandler{answer.PlayerExist})
	// AuctionGameInitCommand is sent during the post-login bootstrap by newer
	// CN clients. The current backend has no auction state yet, but an empty
	// successful response is enough for the client to continue loading.
	packets.RegisterPacketHandler(23430, []packets.PacketHandler{func(_ *[]byte, c *connection.Client) (int, int, error) {
		response := protobuf.SC_20008{Result: proto.Uint32(0)}
		return c.SendMessage(23431, &response)
	}})
	packets.RegisterPacketHandler(11001, []packets.PacketHandler{
		answer.LastLogin,
		answer.PlayerInfo,
		answer.PlayerBuffs,
		answer.GetMetaProgress,
		answer.LastOnlineInfo,
		answer.ResourcesInfo,
		answer.EventData,
		answer.Meowfficers,
		answer.CommanderCollection,
		answer.OngoingBuilds,
		answer.PlayerDock,
		answer.CommanderDock,
		answer.CommanderFleet,
		answer.CommanderOwnedSkins,
		answer.TechnologyRefreshList,
		answer.ShipyardData,
		answer.TechnologyNationProxy,
		answer.CommanderStoryProgress,
		answer.EventCollectionInfo,
		answer.CommanderCommissionsFleet,
		answer.ShopData,
		answer.WorldBaseInfo,
		answer.ChapterBaseSync,
		answer.EquipedSpecialWeapons,
		answer.EquippedWeaponSkin,
		answer.OwnedItems,
		answer.CommanderMissions,
		answer.WeeklyMissions,
		answer.ActivityTaskStateSync,
		answer.DormData,
		// SC_28000 (宿舍计划 / Dorm3D). The client never sends CS_28000 - it only builds
		// ApartmentProxy.roomData from the SC_28000 payload that arrives here
		// (model/proxy/apartmentproxy.lua:22-38). Without it roomData stays empty,
		// SelectDorm3DScene renders every room as locked
		// (view/dorm3d/selectdorm3dscene.lua:190 -> getRoom(id) is nil -> "lock"),
		// and the unlock button's CS_28001 gets rejected because the server already
		// considers the room unlocked - which the client surfaces as "无效操作".
		answer.Dorm3dApartmentData,
		answer.FleetEnergyRecoverTime,
		answer.GameMailbox,
		answer.CompensateNotification,
		answer.CommanderFriendList,
		answer.Activities,
		answer.PermanentActivites,
		answer.GameNotices,
		answer.SendPlayerShipCount,
	})
	packets.RegisterPacketHandler(25026, []packets.PacketHandler{answer.GetCommanderHome})
	packets.RegisterPacketHandler(63001, []packets.PacketHandler{answer.StartTechnologyResearch})
	packets.RegisterPacketHandler(63003, []packets.PacketHandler{answer.FinishTechnologyResearch})
	packets.RegisterPacketHandler(63005, []packets.PacketHandler{answer.StopTechnologyResearch})
	packets.RegisterPacketHandler(63007, []packets.PacketHandler{answer.RefreshTechnologyProjects})
	packets.RegisterPacketHandler(63009, []packets.PacketHandler{answer.ChangeRefreshTechnologyTendency})
	packets.RegisterPacketHandler(63011, []packets.PacketHandler{answer.SelectTechnologyCatchupTarget})
	packets.RegisterPacketHandler(63013, []packets.PacketHandler{answer.JoinTechnologyQueue})
	packets.RegisterPacketHandler(63015, []packets.PacketHandler{answer.FinishQueueTechnology})
	packets.RegisterPacketHandler(50003, []packets.PacketHandler{answer.SendFriendRequest})
	packets.RegisterPacketHandler(50006, []packets.PacketHandler{answer.AcceptFriendRequest})
	packets.RegisterPacketHandler(50009, []packets.PacketHandler{answer.RejectFriendRequest})
	packets.RegisterPacketHandler(25002, []packets.PacketHandler{answer.CommanderBuildBoxStart})
	packets.RegisterPacketHandler(25004, []packets.PacketHandler{answer.CommanderClaimBox})
	packets.RegisterPacketHandler(25006, []packets.PacketHandler{answer.CommanderFleetEquip})
	packets.RegisterPacketHandler(25008, []packets.PacketHandler{answer.CommanderUpgrade})
	packets.RegisterPacketHandler(25010, []packets.PacketHandler{answer.FetchCommanderCandidateTalents})
	packets.RegisterPacketHandler(25012, []packets.PacketHandler{answer.LearnCommanderTalent})
	packets.RegisterPacketHandler(25014, []packets.PacketHandler{answer.ResetCommanderTalents})
	packets.RegisterPacketHandler(25016, []packets.PacketHandler{answer.SetCommanderLockState})
	packets.RegisterPacketHandler(25018, []packets.PacketHandler{answer.CommanderReserveBox})
	packets.RegisterPacketHandler(25020, []packets.PacketHandler{answer.RenameCommander})
	packets.RegisterPacketHandler(25022, []packets.PacketHandler{answer.SetCommanderPrefabFleet})
	packets.RegisterPacketHandler(25024, []packets.PacketHandler{answer.RenameCommanderPrefabFleet})
	packets.RegisterPacketHandler(25028, []packets.PacketHandler{answer.CommanderCatteryOperation})
	packets.RegisterPacketHandler(25030, []packets.PacketHandler{answer.CommanderCatteryAssign})
	packets.RegisterPacketHandler(25032, []packets.PacketHandler{answer.CommanderCatteryStyle})
	packets.RegisterPacketHandler(25034, []packets.PacketHandler{answer.CommanderBoxesRefresh})
	packets.RegisterPacketHandler(25036, []packets.PacketHandler{answer.CommanderCatterySceneState})
	packets.RegisterPacketHandler(25037, []packets.PacketHandler{answer.CommanderQuicklyFinishBoxes})
	packets.RegisterPacketHandler(34501, []packets.PacketHandler{answer.WorldBossInfo})
	packets.RegisterPacketHandler(34503, []packets.PacketHandler{answer.WorldBossOtherBossLookup})
	packets.RegisterPacketHandler(34505, []packets.PacketHandler{answer.WorldBossDamageRank})
	packets.RegisterPacketHandler(34509, []packets.PacketHandler{answer.WorldBossSupport})
	packets.RegisterPacketHandler(34511, []packets.PacketHandler{answer.WorldBossSubmitAward})
	packets.RegisterPacketHandler(34513, []packets.PacketHandler{answer.WorldBossOvertimeClear})
	packets.RegisterPacketHandler(34515, []packets.PacketHandler{answer.WorldBossStateCheck})
	packets.RegisterPacketHandler(34517, []packets.PacketHandler{answer.WorldBossCacheHpRefresh})
	packets.RegisterPacketHandler(34519, []packets.PacketHandler{answer.WorldBossGetOtherFormation})
	packets.RegisterPacketHandler(34521, []packets.PacketHandler{answer.ActivateWorldBoss})
	packets.RegisterPacketHandler(34523, []packets.PacketHandler{answer.WorldBossArchivesAutoBattleStart})
	packets.RegisterPacketHandler(34525, []packets.PacketHandler{answer.WorldBossArchivesStopAutoBattle})
	packets.RegisterPacketHandler(34527, []packets.PacketHandler{answer.SwitchWorldBossArchives})
	packets.RegisterPacketHandler(63301, []packets.PacketHandler{answer.MetaCharacterRepair})
	packets.RegisterPacketHandler(63303, []packets.PacketHandler{answer.MetaCharActiveEnergy})
	packets.RegisterPacketHandler(63305, []packets.PacketHandler{answer.MetaCharacterUnlockShip})
	packets.RegisterPacketHandler(70001, []packets.PacketHandler{answer.MetaCharacterRepairLegacy})
	packets.RegisterPacketHandler(70003, []packets.PacketHandler{answer.MetaCharActiveEnergyLegacy})
	packets.RegisterPacketHandler(70005, []packets.PacketHandler{answer.MetaCharacterUnlockShipLegacy})
	packets.RegisterPacketHandler(63307, []packets.PacketHandler{answer.MetaCharacterTacticsSwitchCommandResponse})
	packets.RegisterPacketHandler(63309, []packets.PacketHandler{answer.MetaCharacterTacticsLevelUpCommandResponse})
	packets.RegisterPacketHandler(63311, []packets.PacketHandler{answer.MetaCharacterTacticsUnlockCommandResponse})
	packets.RegisterPacketHandler(63313, []packets.PacketHandler{answer.MetaCharacterTacticsRequestCommandResponse})
	packets.RegisterPacketHandler(63317, []packets.PacketHandler{answer.MetaCharacterTacticsInfoRequestCommandResponse})
	packets.RegisterPacketHandler(63200, []packets.PacketHandler{answer.StartShipBlueprintDevelopment})
	packets.RegisterPacketHandler(63202, []packets.PacketHandler{answer.FinishShipBlueprint})
	packets.RegisterPacketHandler(63204, []packets.PacketHandler{answer.ModShipBlueprint})
	packets.RegisterPacketHandler(63206, []packets.PacketHandler{answer.StopShipBlueprint})
	packets.RegisterPacketHandler(63208, []packets.PacketHandler{answer.ResumeShipBlueprint})
	packets.RegisterPacketHandler(63210, []packets.PacketHandler{answer.UseTechSpeedupItem})
	packets.RegisterPacketHandler(63212, []packets.PacketHandler{answer.PursueShipBlueprint})
	packets.RegisterPacketHandler(63214, []packets.PacketHandler{answer.ItemUnlockShipBlueprint})
	packets.RegisterPacketHandler(63319, []packets.PacketHandler{answer.MetaQuickTacticsUseBooks})
	packets.RegisterPacketHandler(34001, []packets.PacketHandler{answer.GetMetaShipsPointsResponse})
	packets.RegisterPacketHandler(34003, []packets.PacketHandler{answer.ClaimMetaPtAward})
	packets.RegisterPacketHandler(18001, []packets.PacketHandler{answer.ExerciseEnemies})
	packets.RegisterPacketHandler(18003, []packets.PacketHandler{answer.ExerciseReplaceRivals})
	packets.RegisterPacketHandler(18006, []packets.PacketHandler{answer.ExercisePowerRankList})
	packets.RegisterPacketHandler(18008, []packets.PacketHandler{answer.UpdateExerciseFleet})
	packets.RegisterPacketHandler(18100, []packets.PacketHandler{answer.GetArenaShop})
	packets.RegisterPacketHandler(18102, []packets.PacketHandler{answer.RefreshArenaShop})
	packets.RegisterPacketHandler(18104, []packets.PacketHandler{answer.GetRivalInfo})
	packets.RegisterPacketHandler(18201, []packets.PacketHandler{answer.BillboardRankListPage})
	packets.RegisterPacketHandler(18203, []packets.PacketHandler{answer.BillboardMyRank})
	packets.RegisterPacketHandler(60033, []packets.PacketHandler{answer.GetGuildShop})
	packets.RegisterPacketHandler(60035, []packets.PacketHandler{answer.GuildShopPurchase})
	packets.RegisterPacketHandler(60001, []packets.PacketHandler{answer.CreateGuild})
	packets.RegisterPacketHandler(60005, []packets.PacketHandler{answer.GuildApply})
	packets.RegisterPacketHandler(60010, []packets.PacketHandler{answer.GuildDissolve})
	packets.RegisterPacketHandler(60012, []packets.PacketHandler{answer.SetGuildDuty})
	packets.RegisterPacketHandler(60014, []packets.PacketHandler{answer.GuildFire})
	packets.RegisterPacketHandler(60016, []packets.PacketHandler{answer.GuildImpeach})
	packets.RegisterPacketHandler(60018, []packets.PacketHandler{answer.GuildQuit})
	packets.RegisterPacketHandler(60020, []packets.PacketHandler{answer.AcceptGuildJoinRequest})
	packets.RegisterPacketHandler(60022, []packets.PacketHandler{answer.RejectGuildJoinRequest})
	packets.RegisterPacketHandler(60024, []packets.PacketHandler{answer.GuildListRefresh})
	packets.RegisterPacketHandler(60026, []packets.PacketHandler{answer.ModifyGuildInfo})
	packets.RegisterPacketHandler(60028, []packets.PacketHandler{answer.GuildSearch})
	packets.RegisterPacketHandler(16106, []packets.PacketHandler{answer.GetMedalShop})
	packets.RegisterPacketHandler(16108, []packets.PacketHandler{answer.MedalShopPurchase})
	packets.RegisterPacketHandler(60037, []packets.PacketHandler{answer.CommanderGuildData})
	packets.RegisterPacketHandler(26122, []packets.PacketHandler{answer.GameRoomWeeklyCoinClaim})
	packets.RegisterPacketHandler(26124, []packets.PacketHandler{answer.GameRoomExchangeCoin})
	packets.RegisterPacketHandler(26126, []packets.PacketHandler{answer.GameRoomSuccessSettlement})
	packets.RegisterPacketHandler(26128, []packets.PacketHandler{answer.GameRoomFirstEnterCoinClaim})
	packets.RegisterPacketHandler(26150, []packets.PacketHandler{answer.GetMiniGameShop})
	packets.RegisterPacketHandler(26103, []packets.PacketHandler{answer.MiniGameOperation})
	packets.RegisterPacketHandler(26105, []packets.PacketHandler{answer.MiniGameOperationBatch})
	packets.RegisterPacketHandler(26106, []packets.PacketHandler{answer.ActivityItemList})
	packets.RegisterPacketHandler(26108, []packets.PacketHandler{answer.IslandRequestNodeList})
	packets.RegisterPacketHandler(26110, []packets.PacketHandler{answer.MiniGameTimeSubmit})
	packets.RegisterPacketHandler(26111, []packets.PacketHandler{answer.MiniGameFriendRank})
	packets.RegisterPacketHandler(26152, []packets.PacketHandler{answer.MiniGameShopBuy})
	packets.RegisterPacketHandler(26154, []packets.PacketHandler{answer.MiniGameShopRefresh})
	packets.RegisterPacketHandler(26156, []packets.PacketHandler{answer.FeastGetData})
	packets.RegisterPacketHandler(26158, []packets.PacketHandler{answer.FeastRandomShips})
	packets.RegisterPacketHandler(11506, []packets.PacketHandler{answer.ClickMingShi})
	packets.RegisterPacketHandler(62100, []packets.PacketHandler{answer.CommanderGuildTechnologies})
	packets.RegisterPacketHandler(62002, []packets.PacketHandler{answer.GuildCommitDonate})
	packets.RegisterPacketHandler(62007, []packets.PacketHandler{answer.GuildBuySupply})
	packets.RegisterPacketHandler(62009, []packets.PacketHandler{answer.GuildGetSupplyAwardCommandResponse})
	packets.RegisterPacketHandler(62011, []packets.PacketHandler{answer.GuildFetchCapitalLogCommandResponse})
	packets.RegisterPacketHandler(62013, []packets.PacketHandler{answer.GuildSelectWeeklyTask})
	packets.RegisterPacketHandler(62015, []packets.PacketHandler{answer.GuildUpgradeTechnologyCommandResponse})
	packets.RegisterPacketHandler(62020, []packets.PacketHandler{answer.GuildStartTechGroupCommandResponse})
	packets.RegisterPacketHandler(62022, []packets.PacketHandler{answer.GuildFetchWeeklyTaskProgressCommandResponse})
	packets.RegisterPacketHandler(62024, []packets.PacketHandler{answer.GuildFetchCapitalCommandResponse})
	packets.RegisterPacketHandler(62029, []packets.PacketHandler{answer.GuildGetRankCommandResponse})
	packets.RegisterPacketHandler(26101, []packets.PacketHandler{answer.MiniGameHubData})
	packets.RegisterPacketHandler(26160, []packets.PacketHandler{answer.ActivityStoreData})
	packets.RegisterPacketHandler(24020, []packets.PacketHandler{answer.LimitChallengeInfo})
	packets.RegisterPacketHandler(24022, []packets.PacketHandler{answer.LimitChallengeAward})
	packets.RegisterPacketHandler(24002, []packets.PacketHandler{answer.ChallengeInitial})
	packets.RegisterPacketHandler(24004, []packets.PacketHandler{answer.ChallengeInfo})
	packets.RegisterPacketHandler(24009, []packets.PacketHandler{answer.ChallengeSettle})
	packets.RegisterPacketHandler(24011, []packets.PacketHandler{answer.ChallengeReset})
	packets.RegisterPacketHandler(26002, []packets.PacketHandler{answer.ColoringAchieve})
	packets.RegisterPacketHandler(26004, []packets.PacketHandler{answer.ColoringCell})
	packets.RegisterPacketHandler(26006, []packets.PacketHandler{answer.ColoringClear})
	packets.RegisterPacketHandler(26008, []packets.PacketHandler{answer.ColoringFetch})
	packets.RegisterPacketHandler(26021, []packets.PacketHandler{answer.GetPlayerSummaryInfo})
	packets.RegisterPacketHandler(26031, []packets.PacketHandler{answer.ActivityBossPageUpdate})
	packets.RegisterPacketHandler(26041, []packets.PacketHandler{answer.GetNewServerShop})
	packets.RegisterPacketHandler(26043, []packets.PacketHandler{answer.NewServerShopPurchase})
	packets.RegisterPacketHandler(26051, []packets.PacketHandler{answer.AtelierRequest})
	packets.RegisterPacketHandler(26053, []packets.PacketHandler{answer.AtelierComposite})
	packets.RegisterPacketHandler(26055, []packets.PacketHandler{answer.AtelierRefreshBuff})
	packets.RegisterPacketHandler(26060, []packets.PacketHandler{answer.CityRebuildGetData})
	packets.RegisterPacketHandler(26062, []packets.PacketHandler{answer.CityRebuildEndRecruit})
	packets.RegisterPacketHandler(26064, []packets.PacketHandler{answer.CityRebuildBuildingAction})
	packets.RegisterPacketHandler(26066, []packets.PacketHandler{answer.CityRebuildUpgradeBuff})
	packets.RegisterPacketHandler(26068, []packets.PacketHandler{answer.CityRebuildResultSummary})
	packets.RegisterPacketHandler(26070, []packets.PacketHandler{answer.CityRebuildChooseLevel})
	packets.RegisterPacketHandler(26072, []packets.PacketHandler{answer.CityRebuildInitTime})
	packets.RegisterPacketHandler(64001, []packets.PacketHandler{answer.StartCampTech})
	packets.RegisterPacketHandler(64003, []packets.PacketHandler{answer.FinishCampTechnology})
	packets.RegisterPacketHandler(64005, []packets.PacketHandler{answer.ClaimFleetTechCampAward})
	packets.RegisterPacketHandler(64007, []packets.PacketHandler{answer.ClaimTechnologyCampAwardsOneStep})
	packets.RegisterPacketHandler(64009, []packets.PacketHandler{answer.SetFleetTechAttrAddition})
	packets.RegisterPacketHandler(26081, []packets.PacketHandler{answer.GetBoss4thInfo})
	packets.RegisterPacketHandler(11601, []packets.PacketHandler{answer.EmojiInfoRequest})
	packets.RegisterPacketHandler(11603, []packets.PacketHandler{answer.FetchSecondaryPasswordCommandResponse})
	packets.RegisterPacketHandler(11605, []packets.PacketHandler{answer.SetSecondaryPasswordCommandResponse})
	packets.RegisterPacketHandler(11607, []packets.PacketHandler{answer.SetSecondaryPasswordSettingsCommandResponse})
	packets.RegisterPacketHandler(11609, []packets.PacketHandler{answer.ConfirmSecondaryPasswordCommandResponse})
	packets.RegisterPacketHandler(17005, []packets.PacketHandler{answer.ClaimCollectionAward})
	packets.RegisterPacketHandler(17201, []packets.PacketHandler{answer.FetchVoteTicketInfo})
	packets.RegisterPacketHandler(17203, []packets.PacketHandler{answer.FetchVoteInfo})
	packets.RegisterPacketHandler(16104, []packets.PacketHandler{answer.GetChargeList})
	packets.RegisterPacketHandler(60100, []packets.PacketHandler{answer.CommanderGuildChat})
	packets.RegisterPacketHandler(60007, []packets.PacketHandler{answer.GuildSendMessage})
	packets.RegisterPacketHandler(60102, []packets.PacketHandler{answer.GuildGetUserInfoCommand})
	packets.RegisterPacketHandler(61009, []packets.PacketHandler{answer.GetMyAssaultFleetCommandResponse})
	packets.RegisterPacketHandler(61011, []packets.PacketHandler{answer.GuildGetAssaultFleetCommandResponse})
	packets.RegisterPacketHandler(61003, []packets.PacketHandler{answer.GuildUpdateAssaultFleetCommandResponse})
	packets.RegisterPacketHandler(61013, []packets.PacketHandler{answer.GuildUpdateBossMissionFleetCommandResponse})
	packets.RegisterPacketHandler(61033, []packets.PacketHandler{answer.MarkAssaultShipRecommendCommandResponse})
	packets.RegisterPacketHandler(61035, []packets.PacketHandler{answer.GuildRefreshAssaultRecommendationsCommandResponse})
	packets.RegisterPacketHandler(61001, []packets.PacketHandler{answer.GuildActiveEventCommandResponse})
	packets.RegisterPacketHandler(61005, []packets.PacketHandler{answer.GuildGetActivationEventCommandResponse})
	packets.RegisterPacketHandler(61015, []packets.PacketHandler{answer.GuildFetchBossCommandResponse})
	packets.RegisterPacketHandler(61007, []packets.PacketHandler{answer.GuildJoinMissionCommandResponse})
	packets.RegisterPacketHandler(61017, []packets.PacketHandler{answer.GuildGetReportsCommandResponse})
	packets.RegisterPacketHandler(61019, []packets.PacketHandler{answer.SubmitGuildReportCommandResponse})
	packets.RegisterPacketHandler(61023, []packets.PacketHandler{answer.GuildRefreshMissionCommandResponse})
	packets.RegisterPacketHandler(61025, []packets.PacketHandler{answer.GuildUpdateNodeAnimFlagCommandResponse})
	packets.RegisterPacketHandler(61027, []packets.PacketHandler{answer.GuildGetBossInfoCommandResponse})
	packets.RegisterPacketHandler(61029, []packets.PacketHandler{answer.GuildGetBossRankCommandResponse})
	packets.RegisterPacketHandler(61031, []packets.PacketHandler{answer.GuildJoinEventCommandResponse})
	packets.RegisterPacketHandler(61037, []packets.PacketHandler{answer.GuildGetReportRankCommandResponse})
	packets.RegisterPacketHandler(60003, []packets.PacketHandler{answer.GetGuildRequestsCommandResponse})
	packets.RegisterPacketHandler(13501, []packets.PacketHandler{answer.RemasterSetActiveChapter})
	packets.RegisterPacketHandler(13503, []packets.PacketHandler{answer.RemasterTickets})
	packets.RegisterPacketHandler(13505, []packets.PacketHandler{answer.RemasterInfo})
	packets.RegisterPacketHandler(13507, []packets.PacketHandler{answer.RemasterAwardReceive})
	packets.RegisterPacketHandler(13301, []packets.PacketHandler{answer.EscortQuery})
	packets.RegisterPacketHandler(13401, []packets.PacketHandler{answer.GetSubmarineExpeditionInfo})
	packets.RegisterPacketHandler(13403, []packets.PacketHandler{answer.SubmarineChapterInfo})
	packets.RegisterPacketHandler(11202, []packets.PacketHandler{answer.ActivityOperation})
	packets.RegisterPacketHandler(11204, []packets.PacketHandler{answer.EditActivityFleet})
	packets.RegisterPacketHandler(11206, []packets.PacketHandler{answer.ActivityPermanentStart})
	packets.RegisterPacketHandler(11208, []packets.PacketHandler{answer.ActivityPermanentFinish})
	packets.RegisterPacketHandler(13003, []packets.PacketHandler{answer.EventCollectionStart})
	packets.RegisterPacketHandler(13007, []packets.PacketHandler{answer.EventGiveUp})
	packets.RegisterPacketHandler(13009, []packets.PacketHandler{answer.EventFlush})
	packets.RegisterPacketHandler(13005, []packets.PacketHandler{answer.EventFinish})
	packets.RegisterPacketHandler(11751, []packets.PacketHandler{answer.RefluxRequestData})
	packets.RegisterPacketHandler(11722, []packets.PacketHandler{answer.InstagramChatActivateTopic})
	packets.RegisterPacketHandler(11005, []packets.PacketHandler{answer.AttireApply})
	packets.RegisterPacketHandler(11007, []packets.PacketHandler{answer.ChangePlayerName})
	packets.RegisterPacketHandler(11009, []packets.PacketHandler{answer.ChangeManifesto})
	packets.RegisterPacketHandler(11016, []packets.PacketHandler{answer.UpdateGuideIndex})
	packets.RegisterPacketHandler(11017, []packets.PacketHandler{answer.UpdateStory})
	packets.RegisterPacketHandler(11025, []packets.PacketHandler{answer.SurveyRequest})
	packets.RegisterPacketHandler(11027, []packets.PacketHandler{answer.SurveyState})
	packets.RegisterPacketHandler(11030, []packets.PacketHandler{answer.ChangeLivingAreaCover})
	packets.RegisterPacketHandler(11032, []packets.PacketHandler{answer.UpdateStoryList})
	packets.RegisterPacketHandler(10100, []packets.PacketHandler{answer.SendHeartbeat})
	packets.RegisterPacketHandler(11100, []packets.PacketHandler{answer.HandleConsoleCommand})
	packets.RegisterPacketHandler(11013, []packets.PacketHandler{answer.GiveResources})
	packets.RegisterPacketHandler(15002, []packets.PacketHandler{answer.UseItem})
	packets.RegisterPacketHandler(15004, []packets.PacketHandler{answer.HandleLegacyItemOperation})
	packets.RegisterPacketHandler(15006, []packets.PacketHandler{answer.ComposeItem})
	packets.RegisterPacketHandler(15012, []packets.PacketHandler{answer.QuickExchangeBlueprint})
	packets.RegisterPacketHandler(15008, []packets.PacketHandler{answer.SellItem})
	packets.RegisterPacketHandler(15010, []packets.PacketHandler{answer.ProposeExchangeRing})
	packets.RegisterPacketHandler(33000, []packets.PacketHandler{answer.WorldCheckInfo})
	packets.RegisterPacketHandler(33101, []packets.PacketHandler{answer.WorldActivate})
	packets.RegisterPacketHandler(33103, []packets.PacketHandler{answer.WorldMapOperation})
	packets.RegisterPacketHandler(33106, []packets.PacketHandler{answer.WorldMapRequest})
	packets.RegisterPacketHandler(33108, []packets.PacketHandler{answer.WorldStaminaExchange})
	packets.RegisterPacketHandler(33110, []packets.PacketHandler{answer.WorldTypedDataOperation})
	packets.RegisterPacketHandler(33112, []packets.PacketHandler{answer.WorldResetOrKill})
	packets.RegisterPacketHandler(33205, []packets.PacketHandler{answer.WorldTriggerTask})
	packets.RegisterPacketHandler(33207, []packets.PacketHandler{answer.WorldSubmitTask})
	packets.RegisterPacketHandler(33401, []packets.PacketHandler{answer.WorldPortRequest})
	packets.RegisterPacketHandler(33403, []packets.PacketHandler{answer.WorldPortShopping})
	packets.RegisterPacketHandler(33405, []packets.PacketHandler{answer.WorldFleetChangeCompatibility})
	packets.RegisterPacketHandler(33407, []packets.PacketHandler{answer.WorldShipRepair})
	packets.RegisterPacketHandler(33409, []packets.PacketHandler{answer.WorldFleetRedeploy})
	packets.RegisterPacketHandler(33413, []packets.PacketHandler{answer.WorldDailyTaskRefresh})
	packets.RegisterPacketHandler(33415, []packets.PacketHandler{answer.WorldTriggerDailyTask})
	packets.RegisterPacketHandler(33509, []packets.PacketHandler{answer.WorldChunk3BossSupport})
	packets.RegisterPacketHandler(33602, []packets.PacketHandler{answer.WorldAchieveClaim})
	packets.RegisterPacketHandler(33301, []packets.PacketHandler{answer.WorldItemUse})
	packets.RegisterPacketHandler(10994, []packets.PacketHandler{answer.CheaterMark})
	packets.RegisterPacketHandler(10996, []packets.PacketHandler{answer.VersionCheck})
	packets.RegisterPacketHandler(29001, []packets.PacketHandler{answer.NewEducateRequest})
	packets.RegisterPacketHandler(29003, []packets.PacketHandler{answer.NewEducateGetEndings})
	packets.RegisterPacketHandler(29005, []packets.PacketHandler{answer.NewEducateSelectEnding})
	packets.RegisterPacketHandler(29007, []packets.PacketHandler{answer.NewEducateReset})
	packets.RegisterPacketHandler(29009, []packets.PacketHandler{answer.NewEducateSetCall})
	packets.RegisterPacketHandler(29011, []packets.PacketHandler{answer.NewEducateMainEvent})
	packets.RegisterPacketHandler(29013, []packets.PacketHandler{answer.NewEducateAssess})
	packets.RegisterPacketHandler(29015, []packets.PacketHandler{answer.NewEducateGetTopics})
	packets.RegisterPacketHandler(29017, []packets.PacketHandler{answer.NewEducateSelectTopic})
	packets.RegisterPacketHandler(29019, []packets.PacketHandler{answer.NewEducateGetTalents})
	packets.RegisterPacketHandler(29021, []packets.PacketHandler{answer.NewEducateRefreshTalent})
	packets.RegisterPacketHandler(29023, []packets.PacketHandler{answer.NewEducateSelectTalent})
	packets.RegisterPacketHandler(29025, []packets.PacketHandler{answer.NewEducateChangePhase})
	packets.RegisterPacketHandler(29027, []packets.PacketHandler{answer.NewEducateUpgradeFavor})
	packets.RegisterPacketHandler(29030, []packets.PacketHandler{answer.NewEducateTriggerNode})
	packets.RegisterPacketHandler(29032, []packets.PacketHandler{answer.NewEducateClearNodeChain})
	packets.RegisterPacketHandler(29040, []packets.PacketHandler{answer.NewEducateSchedule})
	packets.RegisterPacketHandler(29042, []packets.PacketHandler{answer.NewEducateNextPlan})
	packets.RegisterPacketHandler(29044, []packets.PacketHandler{answer.NewEducateUpgradePlan})
	packets.RegisterPacketHandler(29046, []packets.PacketHandler{answer.NewEducateScheduleSkip})
	packets.RegisterPacketHandler(29048, []packets.PacketHandler{answer.NewEducateGetExtraDrop})
	packets.RegisterPacketHandler(29050, []packets.PacketHandler{answer.NewEducateEnterAssess})
	packets.RegisterPacketHandler(29072, []packets.PacketHandler{answer.NewEducateRefreshShop})
	packets.RegisterPacketHandler(29101, []packets.PacketHandler{answer.NewEducateGiveUpChoice})
	packets.RegisterPacketHandler(29103, []packets.PacketHandler{answer.NewEducateMakeChoice})
	packets.RegisterPacketHandler(29105, []packets.PacketHandler{answer.NewEducateRefreshChoice})
	packets.RegisterPacketHandler(29107, []packets.PacketHandler{answer.NewEducateRequestChoices})
	packets.RegisterPacketHandler(29120, []packets.PacketHandler{answer.NewEducateReplaceTarot})
	packets.RegisterPacketHandler(29122, []packets.PacketHandler{answer.NewEducateUpgradeEntry})
	packets.RegisterPacketHandler(29124, []packets.PacketHandler{answer.NewEducateGiveUpEntryUp})
	packets.RegisterPacketHandler(29126, []packets.PacketHandler{answer.NewEducateGetChoose})
	packets.RegisterPacketHandler(29060, []packets.PacketHandler{answer.NewEducateGetMap})
	packets.RegisterPacketHandler(29062, []packets.PacketHandler{answer.NewEducateMapNormal})
	packets.RegisterPacketHandler(29064, []packets.PacketHandler{answer.NewEducateMapEvent})
	packets.RegisterPacketHandler(29066, []packets.PacketHandler{answer.NewEducateShopping})
	packets.RegisterPacketHandler(29068, []packets.PacketHandler{answer.NewEducateMapShip})
	packets.RegisterPacketHandler(29070, []packets.PacketHandler{answer.NewEducateUpgradeNormalSite})
	packets.RegisterPacketHandler(29090, []packets.PacketHandler{answer.NewEducateSelectMind})
	packets.RegisterPacketHandler(29092, []packets.PacketHandler{answer.NewEducateRefresh})
	packets.RegisterPacketHandler(30101, []packets.PacketHandler{answer.CompensateNotification})
	packets.RegisterPacketHandler(28000, []packets.PacketHandler{answer.Dorm3dApartmentData})
	packets.RegisterPacketHandler(28001, []packets.PacketHandler{answer.Dorm3dRoomUnlock})
	packets.RegisterPacketHandler(28003, []packets.PacketHandler{answer.Dorm3dTriggerFavor})
	packets.RegisterPacketHandler(28005, []packets.PacketHandler{answer.Dorm3dApartmentLevelUp})
	packets.RegisterPacketHandler(28007, []packets.PacketHandler{answer.Dorm3dReplaceFurniture})
	packets.RegisterPacketHandler(28009, []packets.PacketHandler{answer.HandleDorm3dGiveGift})
	packets.RegisterPacketHandler(28011, []packets.PacketHandler{answer.Dorm3dCollectionItem})
	packets.RegisterPacketHandler(28013, []packets.PacketHandler{answer.Dorm3dChangeSkin})
	packets.RegisterPacketHandler(28015, []packets.PacketHandler{answer.Dorm3dTalk})
	packets.RegisterPacketHandler(28017, []packets.PacketHandler{answer.SelectDorm3dEnter})
	packets.RegisterPacketHandler(28019, []packets.PacketHandler{answer.Dorm3dRoomInviteUnlock})
	packets.RegisterPacketHandler(28021, []packets.PacketHandler{answer.Dorm3dSetCall})
	packets.RegisterPacketHandler(28023, []packets.PacketHandler{answer.Dorm3dChatTriggerEvent})
	packets.RegisterPacketHandler(28026, []packets.PacketHandler{answer.HandleDorm3dInstagramAction})
	packets.RegisterPacketHandler(28028, []packets.PacketHandler{answer.Dorm3dInstagramDiscuss})
	packets.RegisterPacketHandler(28030, []packets.PacketHandler{answer.Dorm3dChatSetBackground})
	packets.RegisterPacketHandler(28032, []packets.PacketHandler{answer.Dorm3dChatSetCare})
	packets.RegisterPacketHandler(28034, []packets.PacketHandler{answer.Dorm3dInstagramSetTopic})
	packets.RegisterPacketHandler(28036, []packets.PacketHandler{answer.Dorm3dRecordVisit})
	packets.RegisterPacketHandler(28038, []packets.PacketHandler{answer.Dorm3dSetSkinHiddenParts})
	packets.RegisterPacketHandler(12002, []packets.PacketHandler{answer.ShipBuild})
	packets.RegisterPacketHandler(12008, []packets.PacketHandler{answer.BuildQuickFinish})
	packets.RegisterPacketHandler(12011, []packets.PacketHandler{answer.RemouldShip})
	packets.RegisterPacketHandler(12043, []packets.PacketHandler{answer.BuildFinish})
	packets.RegisterPacketHandler(12020, []packets.PacketHandler{answer.HandleShipActionValidate})
	packets.RegisterPacketHandler(12025, []packets.PacketHandler{answer.GetShip})
	packets.RegisterPacketHandler(12027, []packets.PacketHandler{answer.UpgradeStar})
	packets.RegisterPacketHandler(12029, []packets.PacketHandler{answer.HandleShipActionList})
	packets.RegisterPacketHandler(12045, []packets.PacketHandler{answer.ConfirmShip})
	packets.RegisterPacketHandler(12006, []packets.PacketHandler{answer.EquipToShip})
	packets.RegisterPacketHandler(12036, []packets.PacketHandler{answer.UpdateShipEquipmentSkin})
	packets.RegisterPacketHandler(16100, []packets.PacketHandler{answer.SupportShipRequisition})
	packets.RegisterPacketHandler(12047, []packets.PacketHandler{answer.ExchangeShip})
	packets.RegisterPacketHandler(30002, []packets.PacketHandler{answer.SendMailList})
	packets.RegisterPacketHandler(30004, []packets.PacketHandler{answer.GetCollectionMailList})
	packets.RegisterPacketHandler(30006, []packets.PacketHandler{answer.HandleMailBatchAction})
	packets.RegisterPacketHandler(30008, []packets.PacketHandler{answer.DeleteArchivedMail})
	packets.RegisterPacketHandler(30010, []packets.PacketHandler{answer.ExtendMailStoreroomCapacity})
	packets.RegisterPacketHandler(30012, []packets.PacketHandler{answer.WithdrawMailStoreroomResources})
	packets.RegisterPacketHandler(30014, []packets.PacketHandler{answer.GetMailTitleList})
	packets.RegisterPacketHandler(30016, []packets.PacketHandler{answer.CheckLoveLetterItemMail})
	packets.RegisterPacketHandler(30018, []packets.PacketHandler{answer.RepairLoveLetterItemMail})
	packets.RegisterPacketHandler(30102, []packets.PacketHandler{answer.GetCompensateList})
	packets.RegisterPacketHandler(30104, []packets.PacketHandler{answer.GetCompensateReward})
	packets.RegisterPacketHandler(22300, []packets.PacketHandler{answer.CommanderManualInfo})
	packets.RegisterPacketHandler(22302, []packets.PacketHandler{answer.CommanderManualGetTask})
	packets.RegisterPacketHandler(22304, []packets.PacketHandler{answer.CommanderManualGetPtAward})
	packets.RegisterPacketHandler(11701, []packets.PacketHandler{answer.HandleJuustagramAction})
	packets.RegisterPacketHandler(11703, []packets.PacketHandler{answer.JuustagramComment})
	packets.RegisterPacketHandler(11705, []packets.PacketHandler{answer.JuustagramMessageRange})
	packets.RegisterPacketHandler(11710, []packets.PacketHandler{answer.JuustagramData})
	packets.RegisterPacketHandler(11712, []packets.PacketHandler{answer.InstagramChatReply})
	packets.RegisterPacketHandler(11714, []packets.PacketHandler{answer.InstagramChatSetSkin})
	packets.RegisterPacketHandler(11716, []packets.PacketHandler{answer.InstagramChatSetCare})
	packets.RegisterPacketHandler(11718, []packets.PacketHandler{answer.InstagramChatSetTopic})
	packets.RegisterPacketHandler(11720, []packets.PacketHandler{answer.JuustagramReadTip})
	packets.RegisterPacketHandler(11753, []packets.PacketHandler{answer.RefluxSign})
	packets.RegisterPacketHandler(11755, []packets.PacketHandler{answer.RefluxGetPTAward})
	packets.RegisterPacketHandler(11800, []packets.PacketHandler{answer.GetShipCount})
	packets.RegisterPacketHandler(10991, []packets.PacketHandler{answer.GameTracking})
	packets.RegisterPacketHandler(10992, []packets.PacketHandler{answer.NewTracking})
	packets.RegisterPacketHandler(10993, []packets.PacketHandler{answer.TrackCommand})
	packets.RegisterPacketHandler(28090, []packets.PacketHandler{answer.ApartmentTrackEvent})
	packets.RegisterPacketHandler(11212, []packets.PacketHandler{answer.UrExchangeTracking})
	packets.RegisterPacketHandler(11029, []packets.PacketHandler{answer.MainSceneTracking})
	packets.RegisterPacketHandler(11023, []packets.PacketHandler{answer.GetRefundInfo})
	packets.RegisterPacketHandler(11025, []packets.PacketHandler{answer.SurveyRequest})
	packets.RegisterPacketHandler(11027, []packets.PacketHandler{answer.SurveyState})
	packets.RegisterPacketHandler(22101, []packets.PacketHandler{answer.GetShopStreet})
	packets.RegisterPacketHandler(22009, []packets.PacketHandler{answer.HarvestClassResource})
	packets.RegisterPacketHandler(22011, []packets.PacketHandler{answer.UseAddShipExpItem})
	packets.RegisterPacketHandler(22014, []packets.PacketHandler{answer.QuickFinishLearnTactics})
	packets.RegisterPacketHandler(22201, []packets.PacketHandler{answer.StartLearnTactics})
	packets.RegisterPacketHandler(22203, []packets.PacketHandler{answer.CancelLearnTactics})
	packets.RegisterPacketHandler(16001, []packets.PacketHandler{answer.HandleShopPurchase})
	packets.RegisterPacketHandler(16201, []packets.PacketHandler{answer.MonthShopPurchase})
	packets.RegisterPacketHandler(16203, []packets.PacketHandler{answer.MonthShopFlag})
	packets.RegisterPacketHandler(16205, []packets.PacketHandler{answer.CryptolaliaUnlock})
	packets.RegisterPacketHandler(11501, []packets.PacketHandler{answer.HandleChargeStart})
	packets.RegisterPacketHandler(11504, []packets.PacketHandler{answer.HandleChargeConfirm})
	packets.RegisterPacketHandler(11508, []packets.PacketHandler{answer.ExchangeCodeRedeem})
	packets.RegisterPacketHandler(11510, []packets.PacketHandler{answer.HandleChargeFailure})
	packets.RegisterPacketHandler(11513, []packets.PacketHandler{answer.RefundHandleChargeStart})
	packets.RegisterPacketHandler(12004, []packets.PacketHandler{answer.RetireShip})
	packets.RegisterPacketHandler(12017, []packets.PacketHandler{answer.ModShip})
	packets.RegisterPacketHandler(11401, []packets.PacketHandler{answer.ChatRoomChange})
	packets.RegisterPacketHandler(50001, []packets.PacketHandler{answer.SearchFriend})
	packets.RegisterPacketHandler(50011, []packets.PacketHandler{answer.DeleteFriend})
	packets.RegisterPacketHandler(50014, []packets.PacketHandler{answer.FriendSearchList})
	packets.RegisterPacketHandler(50018, []packets.PacketHandler{answer.CommanderFriendBatchGet})
	packets.RegisterPacketHandler(50102, []packets.PacketHandler{answer.ReceiveChatMessage})
	packets.RegisterPacketHandler(50016, []packets.PacketHandler{answer.GetFriendBlacklist})
	packets.RegisterPacketHandler(50105, []packets.PacketHandler{answer.SendFriendMessage})
	packets.RegisterPacketHandler(50107, []packets.PacketHandler{answer.RelieveFriendBlacklist})
	packets.RegisterPacketHandler(50109, []packets.PacketHandler{answer.AddFriendBlacklist})
	packets.RegisterPacketHandler(50111, []packets.PacketHandler{answer.ReportPlayer})
	packets.RegisterPacketHandler(50113, []packets.PacketHandler{answer.GetThemeTemplatePlayerInfo})
	packets.RegisterPacketHandler(12032, []packets.PacketHandler{answer.ProposeShip})
	packets.RegisterPacketHandler(20005, []packets.PacketHandler{answer.SubmitTask})
	packets.RegisterPacketHandler(20007, []packets.PacketHandler{func(b *[]byte, c *connection.Client) (int, int, error) {
		response := protobuf.SC_20008{
			Result: proto.Uint32(1),
		}
		return c.SendMessage(20008, &response)
	}})
	packets.RegisterPacketHandler(20009, []packets.PacketHandler{answer.UpdateTaskProgress})
	packets.RegisterPacketHandler(20011, []packets.PacketHandler{answer.SubmitTaskBatch})
	packets.RegisterPacketHandler(20013, []packets.PacketHandler{answer.SubmitQuickTask})
	packets.RegisterPacketHandler(20016, []packets.PacketHandler{answer.TaskProgressEvent})
	packets.RegisterPacketHandler(20205, []packets.PacketHandler{answer.SubmitActivityTask})
	packets.RegisterPacketHandler(20207, []packets.PacketHandler{answer.QuickFinishActivityTask})
	packets.RegisterPacketHandler(20209, []packets.PacketHandler{answer.UpdateLowPriorityActivityTaskProgress})
	packets.RegisterPacketHandler(11011, []packets.PacketHandler{answer.UpdateSecretaries})
	packets.RegisterPacketHandler(12038, []packets.PacketHandler{answer.UpgradeShipMaxLevel})
	packets.RegisterPacketHandler(12040, []packets.PacketHandler{answer.SetFavoriteShip})
	packets.RegisterPacketHandler(12022, []packets.PacketHandler{answer.ChangeShipLockState})
	packets.RegisterPacketHandler(12202, []packets.PacketHandler{answer.ChangeSelectedSkin})
	packets.RegisterPacketHandler(12204, []packets.PacketHandler{answer.ToggleRandomFlagShip})
	packets.RegisterPacketHandler(12206, []packets.PacketHandler{answer.ChangeRandomFlagShipMode})
	packets.RegisterPacketHandler(12208, []packets.PacketHandler{answer.ChangeRandomFlagShips})
	packets.RegisterPacketHandler(12210, []packets.PacketHandler{answer.FinishPhantomQuest})
	packets.RegisterPacketHandler(12212, []packets.PacketHandler{answer.GetPhantomQuestProgress})
	packets.RegisterPacketHandler(14002, []packets.PacketHandler{answer.UpgradeEquipmentOnShip})
	packets.RegisterPacketHandler(14006, []packets.PacketHandler{answer.CompositeEquipment})
	packets.RegisterPacketHandler(14004, []packets.PacketHandler{answer.UpgradeEquipmentInBag})
	packets.RegisterPacketHandler(14008, []packets.PacketHandler{answer.DestroyEquipments})
	packets.RegisterPacketHandler(14010, []packets.PacketHandler{answer.RevertEquipment})
	packets.RegisterPacketHandler(14013, []packets.PacketHandler{answer.TransformEquipmentOnShip})
	packets.RegisterPacketHandler(14015, []packets.PacketHandler{answer.TransformEquipmentInBag})
	packets.RegisterPacketHandler(14201, []packets.PacketHandler{answer.EquipSpWeapon})
	packets.RegisterPacketHandler(14203, []packets.PacketHandler{answer.UpgradeSpWeapon})
	packets.RegisterPacketHandler(14205, []packets.PacketHandler{answer.ReforgeSpWeapon})
	packets.RegisterPacketHandler(14207, []packets.PacketHandler{answer.ConfirmReforgeSpWeapon})
	packets.RegisterPacketHandler(14209, []packets.PacketHandler{answer.CompositeSpWeapon})
	packets.RegisterPacketHandler(12301, []packets.PacketHandler{answer.RequestPlayerAssistShip})
	packets.RegisterPacketHandler(12400, []packets.PacketHandler{answer.LoveLetterUnlock})
	packets.RegisterPacketHandler(12402, []packets.PacketHandler{answer.LoveLetterClaimRewards})
	packets.RegisterPacketHandler(12404, []packets.PacketHandler{answer.LoveLetterRealizeGift})
	packets.RegisterPacketHandler(12406, []packets.PacketHandler{answer.LoveLetterGetAllData})
	packets.RegisterPacketHandler(12408, []packets.PacketHandler{answer.LoveLetterLevelUp})
	packets.RegisterPacketHandler(12410, []packets.PacketHandler{answer.LoveLetterGetContent})
	packets.RegisterPacketHandler(21509, []packets.PacketHandler{answer.StartIslandHandPlant})
	packets.RegisterPacketHandler(21511, []packets.PacketHandler{answer.IslandClaimHandPlantAward})
	packets.RegisterPacketHandler(21507, []packets.PacketHandler{answer.IslandCollectSlot})
	packets.RegisterPacketHandler(21505, []packets.PacketHandler{answer.IslandGetDelegationAward})
	packets.RegisterPacketHandler(21503, []packets.PacketHandler{answer.IslandFinishDelegation})
	packets.RegisterPacketHandler(21501, []packets.PacketHandler{answer.IslandStartDelegation})
	packets.RegisterPacketHandler(21537, []packets.PacketHandler{answer.IslandAddDelegation})
	packets.RegisterPacketHandler(21427, []packets.PacketHandler{answer.IslandUseDelegationTicket})
	packets.RegisterPacketHandler(21425, []packets.PacketHandler{answer.IslandRemoveExpiredTicket})
	packets.RegisterPacketHandler(21423, []packets.PacketHandler{answer.IslandUseTicket})
	packets.RegisterPacketHandler(21420, []packets.PacketHandler{answer.IslandCloseRestaurant})
	packets.RegisterPacketHandler(21418, []packets.PacketHandler{answer.IslandOpenRestaurant})
	packets.RegisterPacketHandler(21000, []packets.PacketHandler{answer.IslandUpgrade})
	packets.RegisterPacketHandler(21002, []packets.PacketHandler{answer.IslandSetAccessAuthority})
	packets.RegisterPacketHandler(21004, []packets.PacketHandler{answer.IslandSetName})
	packets.RegisterPacketHandler(21006, []packets.PacketHandler{answer.IslandTransferOverflowItems})
	packets.RegisterPacketHandler(21012, []packets.PacketHandler{answer.IslandUpgradeInventory})
	packets.RegisterPacketHandler(21014, []packets.PacketHandler{answer.IslandSellOrConvertItems})
	packets.RegisterPacketHandler(21016, []packets.PacketHandler{answer.IslandShopGetData})
	packets.RegisterPacketHandler(21018, []packets.PacketHandler{answer.IslandShopPurchase})
	packets.RegisterPacketHandler(21408, []packets.PacketHandler{answer.IslandShipOrderOperate})
	packets.RegisterPacketHandler(21416, []packets.PacketHandler{answer.IslandShipOrderSubmit})
	packets.RegisterPacketHandler(21429, []packets.PacketHandler{answer.HandleIslandShipOrderRefresh})
	packets.RegisterPacketHandler(21601, []packets.PacketHandler{answer.HandleIslandShipBreakout})
	packets.RegisterPacketHandler(21603, []packets.PacketHandler{answer.HandleIslandShipAttrLimitUnlock})
	packets.RegisterPacketHandler(21605, []packets.PacketHandler{answer.HandleIslandShipAttrUpgrade})
	packets.RegisterPacketHandler(21607, []packets.PacketHandler{answer.HandleIslandUseShipExpBook})
	packets.RegisterPacketHandler(21609, []packets.PacketHandler{answer.HandleIslandInviteShip})
	packets.RegisterPacketHandler(21611, []packets.PacketHandler{answer.HandleIslandShipSkillUpgrade})
	packets.RegisterPacketHandler(21613, []packets.PacketHandler{answer.HandleIslandGiveGift})
	packets.RegisterPacketHandler(21617, []packets.PacketHandler{answer.HandleIslandChangeDress})
	packets.RegisterPacketHandler(21619, []packets.PacketHandler{answer.IslandBuyRoleSkinColor})
	packets.RegisterPacketHandler(21624, []packets.PacketHandler{answer.IslandSetRoleDressRead})
	packets.RegisterPacketHandler(21626, []packets.PacketHandler{answer.IslandChangeCommanderDress})
	packets.RegisterPacketHandler(21628, []packets.PacketHandler{answer.IslandBuyDressColor})
	packets.RegisterPacketHandler(21702, []packets.PacketHandler{answer.IslandGetNpcActionAward})
	packets.RegisterPacketHandler(21630, []packets.PacketHandler{answer.IslandFollowerOp})
	packets.RegisterPacketHandler(21516, []packets.PacketHandler{answer.HandleIslandStopHandPlantHalfway})
	packets.RegisterPacketHandler(21520, []packets.PacketHandler{answer.IslandUnlockTech})
	packets.RegisterPacketHandler(21522, []packets.PacketHandler{answer.IslandFinishTechImmediate})
	packets.RegisterPacketHandler(12034, []packets.PacketHandler{answer.RenameProposedShip})
	packets.RegisterPacketHandler(27002, []packets.PacketHandler{answer.EducateExecutePlans})
	packets.RegisterPacketHandler(27012, []packets.PacketHandler{answer.EducateGetPlans})
	packets.RegisterPacketHandler(27029, []packets.PacketHandler{answer.EducateReset})
	packets.RegisterPacketHandler(27000, []packets.PacketHandler{answer.EducateRequest})
	packets.RegisterPacketHandler(27004, []packets.PacketHandler{answer.EducateMapSiteOperate})
	packets.RegisterPacketHandler(27006, []packets.PacketHandler{answer.EducateUpgradeFavor})
	packets.RegisterPacketHandler(27008, []packets.PacketHandler{answer.EducateTriggerEnd})
	packets.RegisterPacketHandler(27010, []packets.PacketHandler{answer.EducateGetEndings})
	packets.RegisterPacketHandler(27045, []packets.PacketHandler{answer.EducateRequestOption})
	packets.RegisterPacketHandler(27047, []packets.PacketHandler{answer.EducateRefresh})
	packets.RegisterPacketHandler(27014, []packets.PacketHandler{answer.EducateGetEvents})
	packets.RegisterPacketHandler(27016, []packets.PacketHandler{answer.EducateTriggerEvent})
	packets.RegisterPacketHandler(27019, []packets.PacketHandler{answer.EducateSetTarget})
	packets.RegisterPacketHandler(27023, []packets.PacketHandler{answer.EducateSubmitTask})
	packets.RegisterPacketHandler(27027, []packets.PacketHandler{answer.EducateTriggerSpecEvent})
	packets.RegisterPacketHandler(27031, []packets.PacketHandler{answer.EducateSetCall})
	packets.RegisterPacketHandler(27033, []packets.PacketHandler{answer.EducateShopping})
	packets.RegisterPacketHandler(27035, []packets.PacketHandler{answer.EducateGetTargetAward})
	packets.RegisterPacketHandler(27037, []packets.PacketHandler{answer.EducateAddTaskProgress})
	packets.RegisterPacketHandler(27039, []packets.PacketHandler{answer.EducateAddExtraAttr})
	packets.RegisterPacketHandler(27041, []packets.PacketHandler{answer.ChangeEducateCharacter})
	packets.RegisterPacketHandler(27043, []packets.PacketHandler{answer.EducateRequestShopData})
	packets.RegisterPacketHandler(12102, []packets.PacketHandler{answer.FleetCommit})
	packets.RegisterPacketHandler(12104, []packets.PacketHandler{answer.FleetRename})
	packets.RegisterLocalizedPacketHandler(13101, packets.LocalizedHandler{
		CN: &[]packets.PacketHandler{answer.ChapterTracking},
		EN: &[]packets.PacketHandler{answer.ChapterTracking},
		JP: &[]packets.PacketHandler{answer.ChapterTracking},
		KR: &[]packets.PacketHandler{answer.ChapterTrackingKR},
		TW: &[]packets.PacketHandler{answer.ChapterTracking},
	})
	packets.RegisterPacketHandler(13103, []packets.PacketHandler{answer.HandleChapterAction})
	packets.RegisterPacketHandler(13109, []packets.PacketHandler{answer.GetChapterDropShipList})
	packets.RegisterPacketHandler(13106, []packets.PacketHandler{answer.ChapterBattleResultRequest})
	packets.RegisterPacketHandler(13107, []packets.PacketHandler{func(b *[]byte, c *connection.Client) (int, int, error) {
		response := protobuf.SC_13108{
			Result: proto.Uint32(0),
		}
		return c.SendMessage(13108, &response)
	}})
	packets.RegisterPacketHandler(13111, []packets.PacketHandler{answer.RemoveEliteTargetShip})
	packets.RegisterPacketHandler(40001, []packets.PacketHandler{answer.BeginStage})
	packets.RegisterPacketHandler(40003, []packets.PacketHandler{answer.FinishStage})
	packets.RegisterPacketHandler(40005, []packets.PacketHandler{answer.QuitBattle})
	packets.RegisterPacketHandler(40007, []packets.PacketHandler{answer.DailyQuickBattle})
	packets.RegisterPacketHandler(11019, []packets.PacketHandler{answer.UpdateCommonFlagCommand})
	packets.RegisterPacketHandler(11021, []packets.PacketHandler{answer.CancelCommonFlagCommand})
	packets.RegisterPacketHandler(17101, []packets.PacketHandler{answer.GetShipDiscuss})
	packets.RegisterPacketHandler(17103, []packets.PacketHandler{answer.PostShipEvaluationComment})
	packets.RegisterPacketHandler(17105, []packets.PacketHandler{answer.ZanShipEvaluation})
	packets.RegisterPacketHandler(17107, []packets.PacketHandler{answer.UpdateShipLike})
	packets.RegisterPacketHandler(17109, []packets.PacketHandler{answer.ReportShipEvaluation})
	packets.RegisterPacketHandler(17301, []packets.PacketHandler{answer.ClaimTrophy})
	packets.RegisterPacketHandler(20106, []packets.PacketHandler{answer.SubmitWeeklyTask})
	packets.RegisterPacketHandler(20108, []packets.PacketHandler{answer.SubmitWeeklyTaskBatch})
	packets.RegisterPacketHandler(20110, []packets.PacketHandler{answer.ClaimWeeklyTaskProgressReward})
	packets.RegisterPacketHandler(21010, []packets.PacketHandler{answer.IslandClaimProsperityReward})
	packets.RegisterPacketHandler(21050, []packets.PacketHandler{answer.IslandClaimAchievementAward})
	packets.RegisterPacketHandler(21052, []packets.PacketHandler{answer.IslandSyncAchievementProgress})
	packets.RegisterPacketHandler(21022, []packets.PacketHandler{answer.IslandClaimSeasonPTReward})
	packets.RegisterPacketHandler(21024, []packets.PacketHandler{answer.IslandOrderSync})
	packets.RegisterPacketHandler(21030, []packets.PacketHandler{answer.IslandRandomTaskRefresh})
	packets.RegisterPacketHandler(21020, []packets.PacketHandler{answer.IslandShopPlayerRefresh})
	packets.RegisterPacketHandler(21026, []packets.PacketHandler{answer.IslandUseItem})
	packets.RegisterPacketHandler(21060, []packets.PacketHandler{answer.IslandGoFishing})
	packets.RegisterPacketHandler(21062, []packets.PacketHandler{answer.IslandFishingResult})
	packets.RegisterPacketHandler(21064, []packets.PacketHandler{answer.IslandExchangeLure})
	packets.RegisterPacketHandler(21066, []packets.PacketHandler{answer.IslandExchangeItem})
	packets.RegisterPacketHandler(21200, []packets.PacketHandler{answer.IslandGetData})
	packets.RegisterPacketHandler(21300, []packets.PacketHandler{answer.IslandSetAccessTypeLegacy})
	packets.RegisterPacketHandler(21302, []packets.PacketHandler{answer.IslandAccessOp})
	packets.RegisterPacketHandler(21305, []packets.PacketHandler{answer.IslandUpgradeAgora})
	packets.RegisterPacketHandler(21307, []packets.PacketHandler{answer.IslandSaveAgoraPlacement})
	packets.RegisterPacketHandler(21310, []packets.PacketHandler{answer.IslandSignInGiftClaim})
	packets.RegisterPacketHandler(21326, []packets.PacketHandler{answer.IslandGetCardData})
	packets.RegisterPacketHandler(21328, []packets.PacketHandler{answer.IslandSetCardPhoto})
	packets.RegisterPacketHandler(21330, []packets.PacketHandler{answer.IslandSetCardWord})
	packets.RegisterPacketHandler(21332, []packets.PacketHandler{answer.IslandSettingFlag})
	packets.RegisterPacketHandler(21334, []packets.PacketHandler{answer.IslandGiveCardLike})
	packets.RegisterPacketHandler(21336, []packets.PacketHandler{answer.IslandGiveCardLabel})
	packets.RegisterPacketHandler(21338, []packets.PacketHandler{answer.IslandSetCardAchievements})
	packets.RegisterPacketHandler(21343, []packets.PacketHandler{answer.IslandBookUnlock})
	packets.RegisterPacketHandler(21345, []packets.PacketHandler{answer.IslandBookCollectPoint})
	packets.RegisterPacketHandler(21347, []packets.PacketHandler{answer.IslandBookPointAwardClaim})
	packets.RegisterPacketHandler(21621, []packets.PacketHandler{answer.IslandSetCommanderDressRead})
	packets.RegisterPacketHandler(21008, []packets.PacketHandler{answer.IslandRefreshInviteCode})
	packets.RegisterPacketHandler(21034, []packets.PacketHandler{answer.IslandSetTraceTask})
	packets.RegisterPacketHandler(21032, []packets.PacketHandler{answer.IslandAcceptTask})
	packets.RegisterPacketHandler(21036, []packets.PacketHandler{answer.IslandUpdateTaskProgress})
	packets.RegisterPacketHandler(21038, []packets.PacketHandler{answer.IslandSubmitTask})
	packets.RegisterPacketHandler(21041, []packets.PacketHandler{answer.IslandSubmitTaskOneStep})
	packets.RegisterPacketHandler(21202, []packets.PacketHandler{answer.IslandEnter})
	packets.RegisterPacketHandler(21204, []packets.PacketHandler{answer.IslandExit})
	packets.RegisterPacketHandler(21208, []packets.PacketHandler{answer.HandleIslandQueuePoll})
	packets.RegisterPacketHandler(21209, []packets.PacketHandler{answer.IslandSyncControl})
	packets.RegisterPacketHandler(21211, []packets.PacketHandler{answer.IslandSyncData})
	packets.RegisterPacketHandler(21213, []packets.PacketHandler{answer.IslandEnterMap})
	packets.RegisterPacketHandler(21215, []packets.PacketHandler{answer.IslandHeartbeat})
	packets.RegisterPacketHandler(21240, []packets.PacketHandler{answer.IslandTradeOp})
	packets.RegisterPacketHandler(21243, []packets.PacketHandler{answer.IslandGetFriendTradeRank})
	packets.RegisterPacketHandler(21229, []packets.PacketHandler{answer.HandleIslandRecordLastPosition})
	packets.RegisterPacketHandler(21230, []packets.PacketHandler{answer.HandleIslandReconnect})
	packets.RegisterPacketHandler(21245, []packets.PacketHandler{answer.IslandTradeInvitation})
	packets.RegisterPacketHandler(21700, []packets.PacketHandler{answer.IslandAnimationOp})
	packets.RegisterPacketHandler(21312, []packets.PacketHandler{answer.IslandSignInInvitation})
	packets.RegisterPacketHandler(21315, []packets.PacketHandler{answer.HandleIslandGetGiftTag})
	packets.RegisterPacketHandler(21323, []packets.PacketHandler{answer.IslandSendChat})
	packets.RegisterPacketHandler(21340, []packets.PacketHandler{answer.IslandUpdateIllustration})
	packets.RegisterPacketHandler(21403, []packets.PacketHandler{answer.IslandReplaceOrder})
	packets.RegisterPacketHandler(21401, []packets.PacketHandler{answer.IslandSubmitCommonOrder})
	packets.RegisterPacketHandler(21410, []packets.PacketHandler{answer.IslandSetOrderTendency})
	packets.RegisterPacketHandler(21414, []packets.PacketHandler{answer.IslandSubmitFirmOrder})
	packets.RegisterPacketHandler(21405, []packets.PacketHandler{answer.IslandSubmitUrgencyOrder})
	packets.RegisterPacketHandler(21412, []packets.PacketHandler{answer.IslandClaimOrderFavorReward})
	packets.RegisterPacketHandler(21431, []packets.PacketHandler{answer.IslandExchangeShipOrderDelegate})
	packets.RegisterPacketHandler(21524, []packets.PacketHandler{answer.HandleIslandWildGatherCollect})
	packets.RegisterPacketHandler(21529, []packets.PacketHandler{answer.HandleIslandWildCollectFragment})
	packets.RegisterPacketHandler(21531, []packets.PacketHandler{answer.HandleIslandWildCollectFragmentSign})
	packets.RegisterPacketHandler(21533, []packets.PacketHandler{answer.HandleIslandCollectionComplete})
	packets.RegisterPacketHandler(21526, []packets.PacketHandler{answer.HandleIslandWildGatherSign})
	// Dorm / Backyard (190xx)
	packets.RegisterPacketHandler(19002, []packets.PacketHandler{answer.AddDormShip})
	packets.RegisterPacketHandler(19004, []packets.PacketHandler{answer.ExitDormShip})
	packets.RegisterPacketHandler(19006, []packets.PacketHandler{answer.BuyDormFurniture})
	packets.RegisterPacketHandler(19008, []packets.PacketHandler{answer.SaveDormFurnitureLayout})
	packets.RegisterPacketHandler(19011, []packets.PacketHandler{answer.ClaimDormIntimacy})
	packets.RegisterPacketHandler(19013, []packets.PacketHandler{answer.ClaimDormMoney})
	packets.RegisterPacketHandler(19015, []packets.PacketHandler{answer.PollDormExpEvents})
	packets.RegisterPacketHandler(19016, []packets.PacketHandler{answer.RenameDorm})
	packets.RegisterPacketHandler(19018, []packets.PacketHandler{answer.ListDormThemes})
	packets.RegisterPacketHandler(19020, []packets.PacketHandler{answer.SaveDormTheme})
	packets.RegisterPacketHandler(19022, []packets.PacketHandler{answer.DeleteDormTheme})
	packets.RegisterPacketHandler(19024, []packets.PacketHandler{answer.GetBackyardVisitor})
	// Backyard theme templates (191xx)
	packets.RegisterPacketHandler(19101, []packets.PacketHandler{answer.VisitBackyard})
	packets.RegisterPacketHandler(19103, []packets.PacketHandler{answer.GetThemeUploadCredentials})
	packets.RegisterPacketHandler(19105, []packets.PacketHandler{answer.ListCustomThemeTemplates})
	packets.RegisterPacketHandler(19107, []packets.PacketHandler{answer.ListLegacyThemeTemplates})
	packets.RegisterPacketHandler(19109, []packets.PacketHandler{answer.SaveCustomThemeTemplate})
	packets.RegisterPacketHandler(19111, []packets.PacketHandler{answer.PublishCustomThemeTemplate})
	packets.RegisterPacketHandler(19113, []packets.PacketHandler{answer.GetThemeByID})
	packets.RegisterPacketHandler(19115, []packets.PacketHandler{answer.ListCollectedThemes})
	packets.RegisterPacketHandler(19117, []packets.PacketHandler{answer.ListPublishedThemeIDs})
	packets.RegisterPacketHandler(19119, []packets.PacketHandler{answer.CollectTheme})
	packets.RegisterPacketHandler(19121, []packets.PacketHandler{answer.LikeTheme})
	packets.RegisterPacketHandler(19123, []packets.PacketHandler{answer.DeleteCustomThemeTemplate})
	packets.RegisterPacketHandler(19125, []packets.PacketHandler{answer.UnpublishCustomThemeTemplate})
	packets.RegisterPacketHandler(19127, []packets.PacketHandler{answer.CancelThemeCollection})
	packets.RegisterPacketHandler(19129, []packets.PacketHandler{answer.ReportTheme})
	packets.RegisterPacketHandler(19131, []packets.PacketHandler{answer.GetThemePreviewMD5s})
	// Island agora themes (2131x)
	packets.RegisterPacketHandler(21317, []packets.PacketHandler{answer.SaveIslandAgoraTheme})
	packets.RegisterPacketHandler(21319, []packets.PacketHandler{answer.DeleteIslandAgoraTheme})
	packets.RegisterPacketHandler(21321, []packets.PacketHandler{answer.ListIslandAgoraThemes})
	packets.RegisterPacketHandler(17401, []packets.PacketHandler{answer.ChangeMedalDisplay})
	packets.RegisterPacketHandler(17601, []packets.PacketHandler{answer.EquipCodeShareListRequest})
	packets.RegisterPacketHandler(17603, []packets.PacketHandler{answer.EquipCodeShare})
	packets.RegisterPacketHandler(17605, []packets.PacketHandler{answer.EquipCodeLike})
	packets.RegisterPacketHandler(17607, []packets.PacketHandler{answer.EquipCodeImpeach})
	packets.RegisterPacketHandler(17501, []packets.PacketHandler{answer.UnlockAppreciateGallery})
	packets.RegisterPacketHandler(17503, []packets.PacketHandler{answer.UnlockAppreciateMusic})
	packets.RegisterPacketHandler(17505, []packets.PacketHandler{answer.ToggleAppreciationGalleryLike})
	packets.RegisterPacketHandler(17507, []packets.PacketHandler{answer.ToggleAppreciationMusicLike})
	packets.RegisterPacketHandler(17509, []packets.PacketHandler{answer.MarkMangaRead})
	packets.RegisterPacketHandler(17511, []packets.PacketHandler{answer.ToggleMangaLike})
	packets.RegisterPacketHandler(17513, []packets.PacketHandler{answer.UpdateAppreciationMusicPlayerSettings})
	packets.RegisterPacketHandler(15300, []packets.PacketHandler{func(b *[]byte, c *connection.Client) (int, int, error) {
		return 0, 0, nil
	}})
	packets.RegisterPacketHandler(12299, []packets.PacketHandler{func(b *[]byte, c *connection.Client) (int, int, error) {
		return 0, 0, nil
	}})
}
